FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["c:\\Users\\jonas\\Downloads\\raygui-3.2\\raygui-3.2\\src\\raygui.h"]

[MainWindow]
X = 0
Y = 0
Width = 1858
Height = 1096
ShowKind = "Normal"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 347.0
RequestedHeight = 131.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 112.2223
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 0.8304348
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 833.4
SizePriority = 833.4
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 446.0
RequestedHeight = 161.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 117.7778
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.55558
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.55557
Type = "WatchPanel"
Columns = [{Width = 359.0}, {Width = 670.0}, {Width = 359.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 103.8889
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 1489.4
RequestedHeight = 833.4
SizePriority = 0.8304348
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "raygui.h"
TabWidth = 75.55559
Type = "SourceViewPanel"
FilePath = "c:\\Users\\jonas\\Downloads\\raygui-3.2\\raygui-3.2\\src\\raygui.h"
CursorPos = 32769
VertPos = 19077.53

[[BookmarkFolders]]
Title = ""
